name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
   build-frontend:
         runs-on: ubuntu-latest
         steps:
           - name: get code
             uses: actions/checkout@v4

           - name: setup node.js
             uses: actions/setup-node@v4
             with: 
                node-version: 22

           - name: install dependencies
             working-directory: frontend
             run: npm ci 
            
           - name: build
             working-directory: frontend 
             run: npm run build
             env:
               VITE_API_URL: ${{ secrets.VITE_API_URL}}

   build-backend:
     name: build backend
     runs-on: ubuntu-latest
     steps:
         - name: get code
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with: 
              node-version: 22

         - name: install dependencies
           working-directory: backend
           run: npm ci

         - name: build
           working-directory: backend
           run: npm run build


          



